// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzGRqNi6r6y0zLSjQ97qYwiYgOEaMavFs',
    appId: '1:353415964817:android:88d0c100f2b0065000b730',
    messagingSenderId: '353415964817',
    projectId: 'safeconnex-92054',
    databaseURL: 'https://safeconnex-92054-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safeconnex-92054.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmEfZ3UrLJUu8Jbxhh4s2F3AZd9g93Z5g',
    appId: '1:353415964817:ios:b9eac631a74fe6f800b730',
    messagingSenderId: '353415964817',
    projectId: 'safeconnex-92054',
    databaseURL: 'https://safeconnex-92054-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safeconnex-92054.appspot.com',
    iosBundleId: 'com.safeconnex.app.safeconnex',
  );
}
